---
name: Horde Satis Repo

on:
  # run the workflow everyday at 02:00 UTC
  schedule:
    - cron: '0 2 * * *'
  # in addition, run on every push to the master branch
  push:
    branches:
      - master
    # do not run the workflow when documentation was changed
    paths-ignore:
      - docs/*
      - README.md
      - LICENSE
  # the workflow can also be triggered manually
  workflow_dispatch:

jobs:
  # build the website and deploy it to gh-pages branch of a separate repository
  build:
    runs-on: ubuntu-latest

    steps:
      # clone the repository
      - uses: actions/checkout@v2

      # prepare cache key
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%F")"
        shell: bash

      # cache composer directory and build output to make repo generation faster
      - name: Cache composer directory and build output
        id: composer-and-build-output-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer
            build/output
          key: ${{ runner.os }}-php-${{ steps.get-date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-php-

      # generate the package list and the Satis repo website
      - name: Generate package list and Satis repository website
        run: |
          mkdir -p build
          ln bin/satis.json build/satis.json
          export COMPOSER_HOME="$HOME/.composer"
          composer config -g github-oauth.github.com "${{ secrets.GITHUB_TOKEN }}"
          docker pull "docker.io/composer/satis:latest"
          docker run --rm --init \
            -u $(id -u):$(id -g) \
            -v $(pwd)/build:/build \
            -v "${COMPOSER_HOME}:/composer" \
            composer/satis -vvv --no-ansi --no-interaction build -- \
            /build/satis.json /build/output

      # deploy the website to gh-pages branch of a separate repository
      - name: Deploy Satis Website
        uses: crazy-max/ghaction-github-pages@v2
        with:
          repo: maintaina-com/maintaina-com.github.io
          target_branch: master
          build_dir: build/output/
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.SATIS_DEPLOY_PAT }}
